apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: fiap-cloud-payments
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  RabbitMq__Host: "rabbitmq-service.rabbitmq.svc.cluster.local"
  RabbitMq__Port: "5672"
  RabbitMq__Username: "guest"
  RabbitMq__VirtualHost: "/"
  RabbitMq__Queue: "payments"
  ExternalServices__Users: "http://users-service:8080"
  ExternalServices__Games: "http://games-service:8080"

