apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
  namespace: fiap-cloud-payments
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sql-server-service.sql-server.svc.cluster.local,1433;Initial Catalog=DB_PAYMENTS_FIAP;User Id=sa;Password=Str0ngP@ssw0rd123!;TrustServerCertificate=True;MultipleActiveResultSets=True;"
  JwtSettings__Key: "FNlOsjRCRDxThg/avMv2hnoFpfP1IpcaSB7zFPqNWavKQ225/3LZY9Rf81ALIlHUoVA97L3N8dELYfUdpUAWYA=="
  JwtSettings__Issuer: "FIAP.Cloud.Users"
  JwtSettings__Audience: "FIAP.Cloud.Games"
  JwtSettings__ExpiresInMinutes: "60"
  RabbitMq__Password: "guest"

